### ISSUE TITLE
Microsoft.AspNetCore Assemblies

### ISSUE THREAD

**Issue by rdugre** [stormpath/stormpath-aspnetcore-example#1]
It seems you are using the "Microsoft.AspNet" assemblies in this solution. Why aren't you using the "Microsoft.AspNetCore" assemblies? Are the "Microsoft.AspNetCore" assemblies not currently supported?

I'm unable to get the [Authorize] attribute on my controller to trigger the login page when using the "Microsoft.AspNetCore" assemblies.

**Comment by nbarbettini** [comment]
You're absolutely right, it should be using the new assemblies! I got
delayed yesterday while updating this repository. This is still RC1-era
code. I'll get it fixed this morning.

**Comment by rdugre** [comment]
Excellent! Much appreciated.

**Comment by nbarbettini** [comment]
Hey @rdugre - the example should be 100% RC2-compatible now. Sorry about the hassle!

If you find any other problems, feel free to open new issues!
