### ISSUE TITLE
ScopedLazyUserAccessor isn't returning the current account.

### ISSUE THREAD

**Issue by diveboatslave** [stormpath/stormpath-aspnetcore-example#2]
The StormpathCustomDataHandler and StormpathGroupsHandler both make use of the ScopedLazyUserAccessor to get the IAccount of the current user, but this returns the 
wrong account if you were previously logged in as another user.

I haven't configured a CacheProvider so it's using the in-memory cache. If I login as
one user, then log out, and login as a different user, the ScopedLazyUserAccessor will
return the first IAccount object from the cache, not the current user.

**Comment by nbarbettini** [comment]
Thanks for the report. I'll look into this ASAP.

**Comment by diveboatslave** [comment]
I turned the cachemanager off and ScopedLazyUserAccessor still returned the old IAccount. I've tested this on both OSX and Win10, and get the result.

**Comment by nbarbettini** [comment]
Thanks for your patience @DiveboatSlave. I believe I solved the issue, but I'm going to do a little more testing to make sure. It wasn't a cache issue (ScopedLazyUserAccessor doesn't interact with the cache in that way), but rather a problem with the way I was using `IHttpContextAccessor` that could cause problems when multiple threads are involved.

There's a beta package on the prerelease feed that you can test if you'd like: https://www.myget.org/F/stormpath-aspnetcore/api/v3/index.json

**Comment by nbarbettini** [comment]
If you do have a chance to test the beta package, please let me know the results! 👍

**Comment by diveboatslave** [comment]
I'll check out the beta package tomorrow at work, thanks Nate!

**Comment by nbarbettini** [comment]
Hang on, my additional testing revealed an additional bug. Testing is a wonderful thing 😄 I'll be uploading a new beta package soon.

**Comment by nbarbettini** [comment]
Fixed in [v0.7.0](https://github.com/stormpath/stormpath-aspnetcore/releases/tag/0.7.0). @DiveboatSlave can you test and close if it all looks good?

**Comment by diveboatslave** [comment]
Tested with multiple user accounts, using policies based on group and custom data, and it looks all good. Thanks Nate.

**Comment by nbarbettini** [comment]
Great, thanks for following up. Glad it's all working. 👍 

It's worth mentioning that while Groups are never cached (because the Stormpath .NET SDK doesn't support collection caching), Custom Data is cached for users. So, if it is changed on the Stormpath backend, for example, those changes won't show up immediately. I'm happy to explain further if you want to understand the underlying details.
